### ISSUE TITLE
[Bug] Create a new bot from scratch

### ISSUE THREAD

**Issue by alexisconia** [OfficeDev/BotBuilder-MicrosoftTeams-dotnet#13]
**Describe the bug**
If you create a new bot today, with "Empty Bot" Template, the Teams Middleware is not working.
You get an error "System.MissingMethodException: 'Method not found: 'Void Microsoft.Bot.Connector.Authentication.MicrosoftAppCredentials"

**SDK Version**
Microsoft.Bot.Builder.Teams : 4.0.0-beta1
Microsoft.Bot.Builder: 4.2.2

**.Net Version**
.net core 2.1

**Additional context**
A workaround solution is to downgrade Microsoft.Bot.Builder to 4.1.1

**Comment by RamjotSingh** [comment]
Looking into this

**Comment by alexisconia** [comment]
It's also working with Microsoft.Bot.Builder 4.1.5

**Comment by RamjotSingh** [comment]
Did you see this issue when starting the bot or when the request arrived?

**Comment by alexisconia** [comment]
When the request arrived and you try to get the Teams Context.
On this line:
`
var teamsContext = turnContext.TurnState.Get<ITeamsContext>();
`

**Comment by RamjotSingh** [comment]
I tried up until 4.2.0 and things are working, 4.2.2 looks like an issue though. We will work on it internally and try to get support for 4.2.2 up soon.

**Comment by rickhellenthal** [comment]
I'm still experiencing this issue. The versions i'm using are the same as stated in the question.
The error appears when I try to add the TeamsMiddleware in _Startup.cs_, like this:
`options.Middleware.Add(new TeamsMiddleware(new ConfigurationCredentialProvider(this.Configuration)));`
Even when this is the only thing that references the package.

I tried downgrading the Microsoft.Bot.Builder package to no avail.

The error I'm getting is as follows:

> System.MissingMethodException: Method not found: 'Void Microsoft.Bot.Connector.Authentication.MicrosoftAppCredentials..ctor(System.String, System.String)'. at Microsoft.Bot.Builder.Teams.Middlewares.TeamsMiddleware.GetAppCredentialsAsync(String appId) at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at Microsoft.Bot.Builder.Teams.Middlewares.TeamsMiddleware.GetAppCredentialsAsync(String appId) at Microsoft.Bot.Builder.Teams.Middlewares.TeamsMiddleware.CreateTeamsConnectorClientAsync(String serviceUrl, ClaimsIdentity claimsIdentity) in D:\a\1\s\CSharp\Microsoft.Bot.Builder.Teams\Middlewares\TeamsMiddleware.cs:line 127 at Microsoft.Bot.Builder.Teams.Middlewares.TeamsMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextDelegate, CancellationToken cancellationToken) in D:\a\1\s\CSharp\Microsoft.Bot.Builder.Teams\Middlewares\TeamsMiddleware.cs:line 98 at ilxAskBot.Middleware.IntentRecognizerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken) in C:\Users\rhellenthal\source\repos\projectname\projectname\Middleware\IntentRecognizerMiddleware.cs:line 71 at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\MiddlewareSet.cs:line 55 at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotAdapter.cs:line 167

Any ideas?

**Comment by RamjotSingh** [comment]
For now please use Bot.Builder version 4.2.0. Once this issue is closed, you can use the latest version.

**Comment by rickhellenthal** [comment]
I'm still getting the error on earlier versions of Bot.Builder, I tried the following versions:
- 4.2.2
- 4.2.0
- 4.1.5
- 4.1.1

**Comment by RamjotSingh** [comment]
Would you be able to share the repro? I tried with 4.2.0 and was able to get it working.

**Comment by alexisconia** [comment]
@rickhellenthal @RamjotSingh it's also working for me with 4.2.0

**Comment by rickhellenthal** [comment]
@RamjotSingh While I was fixing another issue I noticed that the environment that ngrok was referring to was a different one than that he bot was running on. When I changed the 'name' of the endpoint in the .bot file I was able to fixed this.

After this the error message about the missing function disappeared as well, so it is working now.

Thank you for your time!
