### ISSUE TITLE
[Bug] Can't upload files to chat

### ISSUE THREAD

**Issue by reynoldsbd** [OfficeDev/BotBuilder-MicrosoftTeams-dotnet#16]
**Describe the bug**

The APIs used to [upload files to a chat](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-files) are not fully implemented by this library. In particular, the `FileConsentCardResponse` and `FileUploadInfo` classes are not provided, and `FileConsentCard` is missing some functionality.

**SDK Version**

4.0.0-beta1

**.Net Version**

.NET Core 2.2

**Expected behavior**

When I call the `ToAttachment` extension method for `FileConsentCard`, the resulting attachment must have `Name` set. [See here for reference](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/blob/master/CSharp/Library/Microsoft.Bot.Connector.Teams.Shared/CardExtensions.cs#L87). Failure to set this property results in cards that do not render on the client.

When a user consents to a `FileConsentCard`, a response is sent to the bot in the form of an "invoke" activity. I should be able to retrieve `FileConsentCardResponse` and `FileUploadInfo` instances from this response and use them to carry out the file upload.

**Additional context**

These types were provided by the previous (pre-v4) version of this library. In this version, it appears that `FileConsentCardResponse` and `FileUploadInfo` are simply missing from the Swagger API definition.

For reference, [here](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/blob/master/CSharp/Library/Microsoft.Bot.Connector.Teams.Shared/Swagger/TeamsAPI.json#L876) is the section of TeamsAPI.json from the old version of this library where these types are defined.

**Comment by RamjotSingh** [comment]
This should be fixed in the latest release.
