### ISSUE TITLE
[Bug] Code to return text response in Wikipedia sample is incorrect

### ISSUE THREAD

**Issue by aosolis** [OfficeDev/BotBuilder-MicrosoftTeams-dotnet#18]
**Describe the bug**
The code in https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-dotnet/blob/master/CSharp/Samples/Microsoft.Bot.Builder.Teams.WikipediaMessagingExtension/Engine/TeamsInvokeActivityHandler.cs#L57 to return a text response to a ME query does not work, results in a "Something went wrong" message.

**SDK Version**

**.Net Version**

**Expected behavior**
Text response

**Screenshots**

**Additional context**
The code is missing a layer of nesting. Body should be a MessagingExtensionResponse, not a MessagingExtensionResult:
```
Body = new MessagingExtensionResponse
{
    ComposeExtension = new MessagingExtensionResult {
        Type = "message",
        Text = "Hello world"
    },
}
```

**Comment by RamjotSingh** [comment]
@aosolis I don't think this is a bug.

TeamsInvokeActivityHandler.cs has following code

```cs
 public async Task<InvokeResponse> HandleMessagingExtensionActionAsync(MessagingExtensionActivityAction messagingExtensionAction)
        {
            try
            {
                return new InvokeResponse
                {
                    Body = new MessagingExtensionResponse
                    {
                        ComposeExtension = await this.searchHandler.GetSearchResultAsync(messagingExtensionAction).ConfigureAwait(false),
                    },
                    Status = 200,
                };
            }
```

Which should achieve the required nesting

**Comment by aosolis** [comment]
The issue is with the code in the catch block.
