### ISSUE TITLE
[Feature] Creating a Channel in Teams

### ISSUE THREAD

**Issue by DamienDoumer** [OfficeDev/BotBuilder-MicrosoftTeams-dotnet#31]
**Description**
After going through the graph api for Microsoft Teams [documentation](https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&tabs=cs), I realised it was possible for an app to create channels inside Teams, if it had the appropriate permissions.
Actually, being able to perform this action right inside a bot will be very useful and time saving, since we are building a support platform which has a bot which requires this, but we can't directly perform this scenario with our bot.

**Describe the solution you'd like**
Create a Teams Channel Directly with a bot.

**Describe alternatives you've considered**
An alternative will be to use Microsoft Graph API, create an application and give it the appropriate permissions. Which is longer than just creating it directly within the bot.

**Comment by RamjotSingh** [comment]
Creating channel requires more complex consent model to prevent abuse. Hence Graph is the right way for achieving this.
