### ISSUE TITLE
The type or namespace name 'TeamsMiddleware' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by AJIXuMuK** [OfficeDev/BotBuilder-MicrosoftTeams-dotnet#34]
**Describe the bug**
I'm trying to use getting started example.
After adding initial code in `Startup.cs` to add Teams Middleware I'm getting the error listed in the title.
Nuget package is installed. Version is below.

**SDK Version**
4.3.0-beta1

**.Net Version**
.NET Core 2.1

**Expected behavior**
Code is compiled with no errors.

**Comment by AJIXuMuK** [comment]
my bad

**Comment by Cocorina** [comment]
Hey @AJIXuMuK 
What was the problem? I am having the same 
Thank you

**Comment by AndrewNagulyak** [comment]
Add reference <PackageReference Include="Microsoft.Bot.Builder.Teams" Version="4.3.0-beta1" />
