### ISSUE TITLE
[Bug] Missing SDK Reference

### ISSUE THREAD

**Issue by kedestin** [OfficeDev/BotBuilder-MicrosoftTeams-dotnet#35]
**Describe the bug**

There is no SDK reference for the dotnet version of the SDK

**SDK Version**

C#/.NET Teams Bot Builder SDK (v3 and v4)

**.Net Version**

N/A

**Screenshots**

![](https://i.imgur.com/qBMuCEg.png)

**Comment by clearab** [comment]
There is no method-level documentation for the Teams bot-builder SDKs, only where it is referenced in the conceptual and how-to articles throughout the documentation library. The javascript SDK you see there is the tab/web SDK, separate from the bot-builder SDKs.

**Comment by kedestin** [comment]
Are there any plans to release method-level documentation?
