### ISSUE TITLE
Unable to get user Email address in 1-1 Private conversation in Microsoft Teams

### ISSUE THREAD

**Issue by satyansh-sagar** [OfficeDev/BotBuilder-MicrosoftTeams-dotnet#39]
Unable to get user Email address in 1-1 Private conversation in Microsoft Teams

**Comment by VKAlwaysWin** [comment]
Hi @satyansh-sagar . Not sure if this is best approach to get email, but you can do something like that:
![image](https://user-images.githubusercontent.com/14337164/63844857-9e03c980-c991-11e9-89f0-043114e58979.png)

This is an example from dialog dc.Context is TurnContext, so you can try this from other place.
Idea is to get conversation members using next code:
await dc.Context.TurnState.Get<IConnectorClient>().Conversations.GetConversationMembersAsync(dc.Context.Activity.Conversation.Id, cancellationToken);

And then use AsTeamsChannelAccount method to build object.

**Comment by satyansh-sagar** [comment]
@VKAlwaysWin  Are you using the same in 1-1 private conversation ?

**Comment by VKAlwaysWin** [comment]
@satyansh-sagar , yes, personal bot (1:1)

**Comment by satyansh-sagar** [comment]
Sure. Here it is.
![thumbnail_image](https://user-images.githubusercontent.com/30821164/63912798-afa9a780-ca4b-11e9-867e-1c3e5ccc0d4e.png)

**Comment by satyansh-sagar** [comment]
I'm getting the an exception message 'Object reference not set to an object'

**Comment by VKAlwaysWin** [comment]
Could you please share what line is throwing exception ? what dialog do you use etc?
In case if this is possible please send full dialog class.

Also what nuget package versions do you use for bot, dialogs etc ?

**Comment by satyansh-sagar** [comment]
I got the workaround here. In C# SDK we need to use below code.

var credentials = new MicrosoftAppCredentials("<yourAppId>", "<yourAppPassword>");
var connector = new ConnectorClient(new Uri(turnContext.Activity.ServiceUrl), credentials);
var conversationId = turnContext.Activity.Conversation.Id;
var userInfo = await connector.Conversations.GetConversationMembersAsync(conversationId );
