### ISSUE TITLE
Roadmap for GA of .Net Teams Bot Builder v4

### ISSUE THREAD

**Issue by vman** [OfficeDev/BotBuilder-MicrosoftTeams-dotnet#40]
Hello, are there any updates on the roadmap for when .Net Teams Bot Builder v4 will be GA? 

I can see this article mentions GA around March 2019 but that doesn't seem to be the case anymore if I am reading correctly: https://developer.microsoft.com/en-us/office/blogs/preview-release-of-net-teams-bot-builder-v4-sdk/

The nuget package is still in beta: https://www.nuget.org/packages/Microsoft.Bot.Builder.Teams/

Thanks!

**Comment by VKAlwaysWin** [comment]
Hi, As I understand from next answer: https://github.com/microsoft/BotBuilder-Samples/issues/1736#issuecomment-526627922

BotBuilder team is working to have Teams extensions as part of BotBuilder. I believe it will available then

**Comment by TechWatching** [comment]
Is there a roadmap available somewhere for GA ?

**Comment by clearab** [comment]
We're currently targeting the 4.6 release of the Bot Framework SDK (early November). You can see additional initial samples here: https://github.com/microsoft/botbuilder-dotnet/tree/master/tests/Teams
