### ISSUE TITLE
1-on-1 conversation badrequest

### ISSUE THREAD

**Issue by BogdanDarius** [OfficeDev/BotBuilder-MicrosoftTeams-dotnet#5]
When using CreateDirectConversationAsync with bot account, user account and an activity to initiate a conversation I get 400 BadRequest: could not parse tenant id, no overload parameters.
I am using Bot Framwork 4.0.
Is there any fix?

**Comment by RamjotSingh** [comment]
Please reopen the issue if this does not fix your issue.

**Comment by BogdanDarius** [comment]
The idea is that I have an azure functions that is trigger at a specific moment via a http trigger.

`var newMessage = Activity.CreateMessageActivity();
 newMessage.Type = ActivityTypes.Message;
 newMessage.Text = message.ToString();

 var connector = new ConnectorClient(new Uri(serviceUrl), 
 Environment.GetEnvironmentVariable("MicrosoftAppId"), 
 Environment.GetEnvironmentVariable("MicrosoftAppPassword"));
 MicrosoftAppCredentials.TrustServiceUrl(serviceUrl, DateTime.MaxValue);

 var botAccount = new ChannelAccount("some bot acccount");
 var userAccount = new ChannelAccount("some user account");

 var result = await connector.Conversations.CreateDirectConversationAsync(botAccount, userAccount, (Activity)newMessage);`

In a previous version of the nuget package Microsoft.Bot.Builder.Teams there was a method CreateOrGetDirectConversation which required a tenant id, that method is not available anymore in 4.0.0-beta1.
