### ISSUE TITLE
No response in 1-on-1 chat

### ISSUE THREAD

**Issue by AndyMDoyle** [OfficeDev/BotBuilder-MicrosoftTeams-dotnet#8]
I'm able to use the Echo sample and get responses back when @'ing the bot from a channel it has been added to, but a 1-on-1 chat with the bot doesn't return any messages back from the bot.

This is what I have done:

1. Cloned this repo
2. Created an new Azure App Service
3. Created a new manifest in App Studio, entered the messaging endpoint https://<site>.azurewebsites.net/api/messages, and all other required info
4. Set the app id and password in appsettings.json
5. Published the sample to Azure App Services
6. Installed the new bot from App Studio for 1-on-1 chat and in a test team

Chatting with the bot in a channel works perfectly.

I can start a new 1-on-1 chat and messages are sent, but nothing comes back.
With VS attached to the App Service for debugging, a break point on EchoBot.OnTurnAsync is never hit from 1-on-1 chat (but it does with messages sent from the channel).

Am I a little too early to the party given this is still in beta?

**Comment by iMicknl** [comment]
Could you check if you are using the `DropChatActivitiesMiddleware`, which will drop all messages coming from 1on1 chats and Group chats.

**Comment by AndyMDoyle** [comment]
`DropChatActivitiesMiddleware` is not being used in the TeamEchoBot project and I haven't changed anything other than the app id and password ain appsettings.json before publishing to Azure.

Troubleshooting in Chrome dev tools I can see the 1-on-1 chat messages being sent to a Teams end-point and returning 200/201 response codes, and then there's a poll for messages, but no replies come back.

If the sample works for your or others, could us being on a Teams TAP be an issue?

**Comment by RamjotSingh** [comment]
I wonder if the message is failing on the bot side (there might be a corner case bug in the code). Attach application insights to the code and check if the requests are coming in to bot or not. That will help us narrow down as to where we need to look for issue.

**Comment by AndyMDoyle** [comment]
Having VS2017 attached via remote debugging, I do not see requests hitting the controller from 1-on-1 chat, but I do see them being hit from a channel conversation.

AI it setup against the app service, but isn't registering things so I will add this to the project and retest in case the error is occuring earlier in the request pipeline.

**Comment by RamjotSingh** [comment]
Bot registration can at times take a while to flow through. Good to know that the bot started working. I will add a tracking item to have guidance on how Bot side issues can be debugged effectively. Do let us know if you have any other concerns around the new SDK. Closing this for now.

**Comment by AndyMDoyle** [comment]
@siduppal  - the bot id is bfb4cef7-de78-4c43-b8c7-56cf2e457d9d

I created the bot directly in Teams App Studio, and then published the project and started testing. So the window would be between when the bot id was created, and when I raised this issue - no more than a few hours in total.

Thanks.
